@HOST = http://localhost:8080/api/v1/user

GET {{HOST}}/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiR2JxOFNZS1Bvb1JIIiwidXNlcm5hbWUiOiJTaG9ob0tsb2xvMjU1IiwiZmlyc3RuYW1lIjoiSWJyYWhlbSIsImxhc3RuYW1lIjoiQWJ1IFNoYWgiLCJhZ2UiOjI0LCJlbWFpbCI6ImlicmFoZW1tYWQzMUBnbWFpbC5jb20iLCJyb2xlIjoiY29hY2giLCJpc01vZGVyYXRvciI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTc0NzU0ODczNH0.ATf9Iqat1jltKC6DZJt0URrPGyyhovrpVlZbe4AhRxA

###
GET {{HOST}}/single/Mw1Qs9XkVr3E
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiR2JxOFNZS1Bvb1JIIiwidXNlcm5hbWUiOiJTaG9ob0tsb2xvMjU1IiwiZmlyc3RuYW1lIjoiSWJyYWhlbSIsImxhc3RuYW1lIjoiQWJ1IFNoYWgiLCJhZ2UiOjI0LCJlbWFpbCI6ImlicmFoZW1tYWQzMUBnbWFpbC5jb20iLCJyb2xlIjoiY29hY2giLCJpc01vZGVyYXRvciI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTc0NzU0ODczNH0.ATf9Iqat1jltKC6DZJt0URrPGyyhovrpVlZbe4AhRxA

###
POST {{HOST}}/create
Content-Type: application/json

{
    "username": "ShohoKlolo255",
    "firstname": "Ibrahem",
    "lastname": "Abu Shah",
    "age": 24,
    "email": "ibrahemmad31@gmail.com",
    "password": "Joker525252",
    "role": "coach",
    "isModerator": true,
    "isAdmin": true
}

###
POST {{HOST}}/login
Content-Type: application/json

{
    "authentication": "ShohoKlolo255",
    "password": "Joker525252"
}

###
POST {{HOST}}/login
Content-Type: application/json

{
    "authentication": "ibrahemmad31@gmail.com",
    "password": "Joker525252"
}

###
PUT {{HOST}}/update/eQkZAyydy6QQ
Content-Type: application/json

{
    "requestType": 0,
    "password": "khaled525252",
    "update": "somsom525252"
}

###
PUT {{HOST}}/update/eQkZAyydy6QQ
Content-Type: application/json

{
    "requestType": 1,
    "password": "somsom525252",
    "update": "khaled@gmail.com"
}

###
DELETE {{HOST}}/delete/Q29IzQmmVgpC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiTXcxUXM5WGtWcjNFIiwiZmlyc3RuYW1lIjoiRGFuaWVsIiwibGFzdG5hbWUiOiJIYXJyaXMiLCJ1c2VybmFtZSI6ImRhbmllbC5oYXJyaXM3OSIsImFnZSI6MzksImVtYWlsIjoiZGFuaWVsLmhhcnJpc0BleGFtcGxlLmNvbSIsInJvbGUiOiJjb2FjaCIsImlzQWRtaW4iOnRydWV9LCJpYXQiOjE3NDc1MDEzNDF9.GZXw5mlRkbAv24j0nSIZRp_o1K7icROJR5zf06NAbLM

###
DELETE {{HOST}}/dee/
